### ISSUE TITLE
numa.h：No such file or directory

### ISSUE THREAD

**Issue by sunningboy** [thu-ml/warplda#1]
## when I run "make -j" , the error:

In file included from /Users/weyn/Downloads/warplda/src/NumaArray.cpp:1:0:
/Users/weyn/Downloads/warplda/src/NumaArray.hpp:4:18: 致命错误：numa.h：No such file or directory
 #include <numa.h>
                  ^
编译中断。
make[2]: **\* [src/CMakeFiles/common.dir/NumaArray.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
In file included from /Users/weyn/Downloads/warplda/src/AdjList.hpp:5:0,
                 from /Users/weyn/Downloads/warplda/src/Bigraph.hpp:3,
                 from /Users/weyn/Downloads/warplda/src/Bigraph.cpp:1:
/Users/weyn/Downloads/warplda/src/NumaArray.hpp:4:18: 致命错误：numa.h：No such file or directory
 #include <numa.h>
                  ^
编译中断。
make[2]: **\* [src/CMakeFiles/common.dir/Bigraph.cpp.o] Error 1
In file included from /Users/weyn/Downloads/warplda/src/AdjList.hpp:5:0,
                 from /Users/weyn/Downloads/warplda/src/AdjList.cpp:1:
/Users/weyn/Downloads/warplda/src/NumaArray.hpp:4:18: 致命错误：numa.h：No such file or directory
 #include <numa.h>
                  ^
编译中断。
make[2]: **\* [src/CMakeFiles/common.dir/AdjList.cpp.o] Error 1
In file included from /Users/weyn/Downloads/warplda/src/Vocab.cpp:2:0:
/Users/weyn/Downloads/warplda/src/Utils.hpp: 在函数‘void Memoryinfo(double&, double&)’中:
/Users/weyn/Downloads/warplda/src/Utils.hpp:157:24: 错误：‘_SC_PHYS_PAGES’在此作用域中尚未声明
   long phypz = sysconf(_SC_PHYS_PAGES);
                        ^
/Users/weyn/Downloads/warplda/src/Utils.hpp:159:25: 错误：‘_SC_AVPHYS_PAGES’在此作用域中尚未声明
   long avphys = sysconf(_SC_AVPHYS_PAGES);
                         ^
make[2]: **\* [src/CMakeFiles/common.dir/Vocab.cpp.o] Error 1

**Comment by sunningboy** [comment]
Chen, Jianfei and Li, Kaiwei and Zhu, Jun and Chen, Wenguang 几位MIT的GG有办法解决吗？

**Comment by chnlkw** [comment]
Please install _libnuma_ package:
CentOS: `yum install libnuma-devel`
Ubuntu: `apt-get install libnuma-dev`

**Comment by cjf00000** [comment]
We will fix this issue later on but for now please try the solution by Kaiwei.

**Comment by sameehj** [comment]
Fedora: dnf install numactl-devel

**Comment by VijaySrivastav** [comment]
For RHEL : 
yum install numactl-devel

**Comment by qinhuan** [comment]
centos6.3 ：sudo yum install numactl-devel.x86_64

**Comment by pantuza** [comment]
For OpenSuse:
```bash
$> zypper install libnuma-devel
```
