### ISSUE TITLE
Does this support distributed training

### ISSUE THREAD

**Issue by xlvector** [thu-ml/warplda#2]
Does warplda support training large dataset from multi-machine.

If yes, how to do this?

**Comment by thu-ml** [comment]
The distributed version has not open-sourced yet. We will make it open source in the near future.

Currently, the single machine version can handle PubMed (8 billion tokens) on a single machine with 64GB RAM.

**Comment by xlvector** [comment]
Thanks very much. Hope you can release distributed version soon.

**Comment by ghost** [comment]
Hello, great work on warplda!! Might there be any updates regarding the open-sourcing of the distributed version?

**Comment by cjf00000** [comment]
We have open-sourced another distributed version, which is faster than WarpLDA. Still working on improving its usability though.

https://github.com/thu-ml/BigTopicModel

**Comment by ghost** [comment]
Great, I'll be sure to check it out! Thank you
