### ISSUE TITLE
Bug report in computing log-likelihood

### ISSUE THREAD

**Issue by lightning77** [thu-ml/warplda#7]
During our test, the released warplda prints out abnormal log-likelihood values when we run it on large dataset.
At the **line 60 of warplda.hpp**, the '**log_likelihood**' variable, which stores the local log-likehood value, is declared as **float** variable. When the log-likelihood becomes large, it fails to manage the value properly. It should be declared as **double** variable.

**Comment by chnlkw** [comment]
Thanks!
PR merged: #8
